version: '3.7'

services:
    certbot:
        image: certbot/certbot
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot

    web:
        image: nginx
        ports:
        - "80:80"
        - "443:443"
        restart: always
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot

            - type: bind
              source: /root/stuff/docker/web-server/storage
              target: /usr/share/nginx/html
              volume:
                nocopy: true
            - type: bind
              source: /root/stuff/docker/web-server/default.conf
              target: /etc/nginx/conf.d/default.conf
              volume:
                nocopy: true
